baseurl = "https://ziwenzu.com"
title = "Ziwen(Gary) Zu"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
math = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Ziwen(Gary) Zu"
    description = "Ziwen Zu's personal website"
    keywords = "academic,political science,personal"
    info = "Ph.D. student in Political Science"
    avatarurl = "/images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "'Qualis ab incepto.'"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/ziwenzu/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ziwenzu"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/zu_gary"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/ziwen-zu-59a964104/"
[[params.social]]
    name = "Weibo"
    icon = "fab weibo"
    weight = 4
    url = "https://www.weibo.com/5406865234/profile?rightmod=1&wvr=6&mod=personinfo"
[[params.social]]
    name = "Google Scholar"
    icon = "ai google-scholar"
    weight = 5
    url = "https://scholar.google.com/citations?hl=en&user=XpVWmF8AAAAJ&view_op=list_works&authuser=1&gmla=AJsN-F4cO7_Uh_uSbJOdxg8rGi19IbpDwT2fY132rQsK-fD18IkdTuurwuvf50zTu-ThuG-iM5ZXO4aoIUc-iNeeiqIYm-Nh2AYL7M2Do-6NQJcKxLOJmx8&gmla=AJsN-F75leTPwt60VoR52WMTiAYr-qm-1Rdtq42yw9QAKf1JfKVA4IonNkn3x_wt0HVD6_lz8fvXiJa-WIAulm5E3aBkkEMgQgHR0IlqLea_Pi8m0xBrB5g&sciund=5995933698653481285&scilu=&scisig=AMD79ooAAAAAXuUDzBptHUte_JUI4sWuWTyhFE5DnpPr&gmla=AJsN-F7-eNdj2goYt7b5W4lkjLz5aTAgwaC92I34xfxFbiffYj5pXcm9stn4tQLF749frRh1ABCXHxtMyw6-CSQGS2Ke2DwVGWw7MVJCiTzEkPIhso-4q0Q&sciund=10107041626739721805
"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"
            
            [[languages.en.menu.main]]
            name = "Music"
            weight = 4
            url = "music/"

            [[languages.en.menu.main]]
            name = "Contact Me"
            weight = 5
            url = "contact/"


    [languages.pt-br]
        languagename = "中文"
        title = "祖梓文"

        [languages.pt-br.params]
            author = "祖梓文"
            info = "Chercheur en Sciences Politiques"
            description = "Site Web Personnel de Tom"
            keywords = "associé de recherche, science politique, personnel"
            footercontent = "'Les véritables leçons sont les institutions que nous détruisons en cours de route.'"

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "À propos de Moi"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Projets"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contactez Moi"
            weight = 5
            url = "contact/"