baseurl = "https://tjbrailey.netlify.app"
title = "Ziwen Zu"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
math = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Ziwen(Gary) Zu"
    description = "Ziwen Zu's personal website"
    keywords = "research,political science,personal"
    info = "Political Science Ph.D. student at UCSD"
    avatarurl = "/images/avatar.jpeg"
    #gravatar = "john.doe@example.com"
    footercontent = "Let there be Light"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ziwenzu"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/zu_gary"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/ziwen-zu-59a964104/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 4
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Research"
            weight = 2
            url = "projects/"
            
            [[languages.en.menu.main]]
            name = "Teaching"
            weight = 3
            url = "teaching/"

            [[languages.en.menu.main]]
            name = "Contact Me"
            weight = 5
            url = "contact/"


    