---
title: "Ridiculously Niche Plots Episode I: Scaled and Faceted Radar Plots"
author: "Tom Brailey"
date: "2020-06-17"
categories: ["R"]
tags: ["test"]
---

Hello and welcome to the first episode in a series I like to call "Ridiculously Niche Plots"! An intermittent series where I give a brief rundown of especially strange plots that I have spent hours trying to crack, in the hope that someone, somewhere, struggling to understand the ins and outs of gridExtra or who are hitting their head against a wall because ggplot2 is throwing out a horrifically labyrinthine error, might stumble on this article and have all of their questions answered. I have certainly spent many hours hoping for the same...

In today's episode, we will be looking at radar plots, specifically, radar plots faceted by country, more specifically, scaled faceted radar plots with axis labels that corresponds to its legend, which groups percentages of military equipment by the domain in which they operate, and where if that percentage is 0, the axis text is grayed-out. 

To many of you I'm sure this sounds elementary, but, honestly, when I figured this out I felt a sense of achievement like no other. So, in the interest of reliving that euphoric moment, here we go! 

Firstly, I do some top-secret data cleaning. 

...

beep boop

...



This yields the above image! Wowee is that a niche plot! 

It's quite cool though, and I'm pretty certain that this text-coloring thing will be really useful, and faceting plots using grid and gridExtra is also great when using loops on big country subsets. So hopefully little bits and pieces of this code will come in handy at some point in the future. 

I posted an issue on stackoverflow while working on this plot and had some super helpful feedback, and in the interest of scientific transparency and credit-giving to the unbelievably altruistic members of the stack community, you can view the discussion [here](https://stackoverflow.com/questions/62413349/color-axis-text-based-on-variable-value-in-a-faceted-plot).

That concludes episode I of Ridiculously Niche Plots! I hope you enjoyed, and brace yourselves for another convoluted-but-potentially-useful plot coming your way soon...