---
title: "From RA to RA"
author: "Tom Brailey"
date: "2020-07-28"
categories: ["Misc"]
tags: ["Research assistant", "Research assoicate"]
---

In June 2020, I finished up my research assistant positions at UC San Diego's (UCSD) political science department, and in July, I began working as a research associate for J-PAL's Payments and Governance Research Program (PGRP), also at UCSD. Now I have been working there for about a month, I wanted to ruminate about the transition from RA to RA. 

Me, being my naive and excitable self, dove head first into PGRP, assuming it to be a full-time version of the work I had been doing for the political science department. A typical workday at the department would go: get tagged in an issue ticket where the task was to create a type of graph, wrangle a dataset in a particular way, or complete a given amount of data-entry. From there, I would spend usually a day or so completing that task, checking-in regularly with my supervisor (either a PhD student or a professor) to clarify questions and arrange next-steps, and then I would move on to the next task. This set up was great for me, quick tasks that usually taught me a new skill--I would be forced to figure out how to make a waffle plot or calculate a certain statistic--and that I could complete in a couple of hours, allowing me to focus on school-related work for the rest of the day. Moreover, I never felt a huge amount of responsibility as I was just working from graph to graph, dataset to dataset, with clear instruction and little room for misunderstanding. 

An aside, I had an absolutely fantastic experience with all the research assistant positions that I held. However, I have colleagues who have had wildly different experiences, and so while this post maintains a warm view toward research assistantships, the darker sides of such positions--not getting paid, being over- and under-worked, workplace misconduct, and the like--need to be acknowledged. 

I enjoyed this style of work, and somewhat foolishly thought that a full-time research associate position would be, in essence, the same. Get given a graph to make or some data to clean or a manuscript to proofread, but all day long. What fun! When you look at the job description for a research assistant and a research associate--in political science and economics at least--they look about the same, and, from my perspective at least, no one ever really distinguished between the two, and so going into my new position, I assumed that, aside from the time commitment, they were the same position. 

In fact, the jump from research assistant to associate was a fairly big one. A lot fo the work is actually quite similar; you spend a lot of time cleaning and analyzing data, making graphs, and so on, but the, for lack of a better word, "vibe", is entirely different. Perhaps the biggest shock to the system is the self-organization piece. No longer am I being instructed to make a specific graph or clean a specific dataset; it is now my job to define the work agenda, what tasks need doing, and in what order. Of course, there is a PI, a project manager, and usually a few other research associates that allow you to talk through ideas a and get clarity, but for the most part, you are in charge of day-to-day operations. Of course, people will come to you with requests, which I certainly enjoy, though this is not the day-to-day norm. I enumerate a couple of tactics that I have implemented since starting my position later, but for me, the lack of explicit guidance has been the biggest challenge for me, coming from a research assistant position. 

The lack of instruction is exacerbated by the position being full-time. As a part-time researcher, I would intersperse work with my classes and extra-cirriculars, and I wouldn't usually focus on work-related tasks for more than three hours at a time. Now, I am up at 7, and I work until 4, and I have to fill my *entire* day with stuff to do! 

Another aside, maybe, in actual fact, the jump from RA to RA is really no big deal, and what actually caused my existential crises was, you know, the big old pandemic that happened at exactly the same time. So I should perhaps say that everything I am saying might want to be taken with a pinch of salt.

Third, and perhaps more logically, the sheer volume and scope of your responsibilities may be overwhelming at first. You will need to familiarize yourself with vast repositories of data, manuscripts, tracking sheets, instruments; long and complicated variable naming conventions; and code that you will have literally no idea of what it is supposed to do. All of these points are to be expected of any new job, but again, if you were me, going into this with a very rudimentary understanding of the concept of "full-time research", it can all seem a little overwhelming. 

So, having worked as a research associate for about a month, what have I learned? Firstly, pandemics suck. Secondly, I enumerate a couple of points below that might be of use if you find yourself transitioning between a research assistantship and a research associate position: 

1. **Ask lots of questions** 
   + Obviously, it is good to try to figure things out for yourself, but set a limit on how much time you are going to spend on trying to make sense of something before reaching out to the right person.
   + Additionally, when asking questions or making requests of others, it is good to:
      + Enumerate any questions to maintain clarity. 
      + Specify a deadline of when you would like them to respond. 
   + It can also be useful to have a "questions/answers" document to keep record of particular issues. It is useful if you need reminding yourself, or if you end up handing your work off to others. 

2. **Keep a list of things to do**
   + Try to keep your documents streamlined, and have all of your to dos in one document. 
   + Not a popular opinion, but I tend to shy away from using colors/fonts/sizes etc., instead crossing out goals as I complete them. 
   + Prioritize in terms of importance, not in terms of how easy something is to achieve. 

3. **Set daily, weekly, and monthly goals**
   + Again, prioritize the important things. Try not to spend your time working on the small things in order to feel a sense of achievement (I say this, but I also do this literally all of the time).
   + Be honest with yourself and with the task in hand. Based on how other tasks similar to this one have gone, how long do you *really* think you will need in order to finish it. 
   + Hold others accountable, and have others hold you accountable in completing these goals. 
   + Sometimes, a task is unexpectedly difficult. If you think it will take longer than planned, and if you promised someone you would get something to them by a deadline, be upfront, clear, and reoganize. 

4. **Document things**
   + If there is a particular facet of the project that is confusing to you, writing it out can be useful.
      + For example, if there is an analysis file that calls in a bunch of other scripts, it could be useful to use an Excel sheet to visualize how all the code files relate to one another. Going further, you could document the inputs into each script, as well as the expected outputs. 
      + Where I have a general understanding of something, and I know that the only way I am going to become super comfortable with it is exposure to it, I find documenting, writing about, or visualizing the thing to be very helpful. 
   + I find using apps like Googlesheets and Googledocs to be the most efficient and the easiest to integrate into my workflow. But as you accrue more and more documents, be them for note-taking, goal-setting, question-answering, and so on, make sure you have a clear and understandable file strucutre. 
      + I have a folder that is comprised of all documents relating to my work. It is clearly and concisely categorized and fairly easy to navigate. My thought process when creating it was to make something that I could one day hand off to the next research associate for them to use. With that in mind, I think having a folder on all things project related can be very useful for you and for the others you work with.